name: ShardSMP
version: 1.0
main: dev.samiel.shardsmp.ShardSMP
api-version: 1.21
description: Shard-based kill streak system
author: Samiel

commands:
  shardx:
    description: Check your ShardX count
    usage: /shardx
  spl:
    description: Spawn a dummy to test shards
    usage: /spl
  shardadmin:
    description: Admin commands for ShardX
    usage: /shardadmin <set|give|take|reset|check> <player> [amount]
